version: '2'
services:
    epurchase-app:
        image: epurchase
        external_links:
            - epurchase-mysql:mysql
            - epurchase-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/epurchase?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    epurchase-mysql:
        extends:
            file: mysql.yml
            service: epurchase-mysql
    epurchase-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: epurchase-elasticsearch
